services:
  ssl-generator:
    image: node:20-bullseye  # Node.js 20 + Debian Bullseye (lightweight and compatible)
    container_name: ssl-generator
    working_dir: /app
    volumes:
      - .:/app                # Map the app source code
      - /data/coolify/proxy/certs:/data/coolify/proxy/certs  # Map Coolify certs
    ports:
      - "3030:3030"            # Expose app on port 8000
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y certbot &&
        npm install &&
        node index.js
      "
    restart: unless-stopped
    environment:
      - SSL_EMAIL  # Email for SSL certificate registration
      - CERT_DIR # Directory for storing certificates
      - NODE_ENV  # Set Node.js environment to production