services:
  ssl-generator:
    image: node:20-bullseye
    container_name: ssl-generator
    working_dir: /app
    volumes:
      - .:/app                # Map the app source code
      - /data/coolify/proxy/certs:/data/coolify/proxy/certs  # Map Coolify certs
    ports:
      - "3030:3030"
    command: >
      bash -c "
        ls -la /app &&
        apt-get update &&
        apt-get install -y certbot python3-certbot-nginx curl &&
        npm install &&
        npm start
      "
    restart: unless-stopped