services:
  ssl-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ssl-generator
    working_dir: /app
    volumes:
      - ./:/app                # Map the app source code
      - /data/coolify/proxy/certs:/data/coolify/proxy/certs  # Map Coolify certs
    ports:
      - "3030:3030"            # Expose port 3030
    environment:
      - DOMAIN=
      - EMAIL=
    restart: unless-stopped
    