services:
  ssl-generator:
    image: node:20-bullseye
    container_name: ssl-generator
    volumes:
      - ./:/app  # This maps your current directory to /app in the container
    working_dir: /app
    command: >
      bash -c "
        ls -la &&
        cat package.json &&
        npm install &&
        node app.js
      "